### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by kevaday** [floydhub/word-language-model#1]
Hi, 
When I run main with the following arguments:
--model GRU --emsize 4096 --nhid 4096 --nlayers 2 --lr 0.005 --epochs 2000 --batch_size 80 --bptt 64 --dropout 0.35 --cuda --save save
I get the following error: TypeError: iteration over a 0-d tensor
Here is the full error:
Traceback (most recent call last):
  File "main.py", line 179, in <module>
    train()
  File "main.py", line 148, in train
    hidden = repackage_hidden(hidden)
  File "main.py", line 112, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "main.py", line 112, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "main.py", line 112, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "main.py", line 112, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "main.py", line 112, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "main.py", line 112, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "main.py", line 112, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "E:\Python\3.6.2\lib\site-packages\torch\tensor.py", line 381, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

This happens before training even starts. I am quite new to PyTorch, so I wasn't able to figure it out on my own. If you could help, it would be great.
Thanks

**Comment by ReDeiPirati** [comment]
Hi @kevaday, 

I have just retested it on FloydHub and is working fine... Here's the command I used:

```bash
floyd run --gpu --data roishachar/datasets/treebank/1:input --env pytorch-0.2 "python main.py --model GRU --emsize 4096 --nhid 4096 --nlayers 2 --lr 0.005 --epochs 2000 --batch_size 80 --bptt 64 --dropout 0.35 --cuda --save save --log-interval 10"
```

What command did you run? Are you working on FloydHub?

Thanks a lot for opening the issue because I've noticed that there was a dummy `quit` statement that I have just removed.

**Comment by kevaday** [comment]
Oh I see what the problem is, I'm not using FloydHub. Although I don't know what it is, I will check it out. Is it available on windows?
And yea, I noticed that dummy quit and i fixed up little bugs like that but that's it, otherwise your code is great! Thanks for the response

**Comment by kevaday** [comment]
Ok, I just found out floyd is a pip package

**Comment by ReDeiPirati** [comment]
> Ok, I just found out floyd is a pip package

FloydHub is a platform for training / testing and deploy deep learning model, here's the link: https://www.floydhub.com.

You can sign in the Beginner Plan which is totally Free!

**Comment by kevaday** [comment]
okay, thanks
